<template>
  <div class="page-section webssh-page">
    <section class="page-card"><div class="page-header with-action"><div><h2>WebSSH 控制台</h2><p>密码仅以加密形式保存在服务端；连接、输入和输出均通过当前登录会话传输。</p></div><el-button class="primary-action small" @click="dialogVisible = true">新增主机</el-button></div>
      <div class="webssh-hosts"><button v-for="host in hosts" :key="host.id" class="webssh-host-card" :class="{ active: activeHost?.id === host.id }" @click="connect(host)"><strong>{{ host.host_name }}</strong><span>{{ host.username }}@{{ host.host }}:{{ host.port }}</span><el-button link type="danger" @click.stop="remove(host)">删除</el-button></button><el-empty v-if="!hosts.length" description="还没有保存 SSH 主机" /></div>
    </section>
    <section class="page-card webssh-terminal-card"><div class="page-header"><div><h2>{{ activeHost ? `终端：${activeHost.host_name}` : '请选择一台主机' }}</h2><p>{{ terminalStatus }}</p></div></div><div ref="terminalRef" class="webssh-terminal"></div></section>
    <el-dialog v-model="dialogVisible" title="保存 SSH 主机" width="520px"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="form.hostName" placeholder="例如：生产服务器" /></el-form-item><div class="form-grid"><el-form-item label="IP 地址 / 域名"><el-input v-model="form.host" placeholder="192.168.1.10" /></el-form-item><el-form-item label="端口"><el-input-number v-model="form.port" :min="1" :max="65535" style="width:100%" /></el-form-item></div><el-form-item label="用户名"><el-input v-model="form.username" placeholder="root" /></el-form-item><el-form-item label="密码"><el-input v-model="form.password" type="password" show-password autocomplete="new-password" /></el-form-item></el-form><p class="form-hint">请仅保存你被授权管理的服务器。删除主机配置不会影响远程服务器。</p><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button class="primary-action small" :loading="saving" @click="save">保存并连接</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import { nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Terminal } from '@xterm/xterm'; import { FitAddon } from '@xterm/addon-fit'; import '@xterm/xterm/css/xterm.css';
import { deleteSshHostApi, getSshHostsApi, saveSshHostApi } from '../../api'; import { getRealtimeSocket } from '../../realtime/socket';
const hosts = ref([]); const activeHost = ref(null); const dialogVisible = ref(false); const saving = ref(false); const terminalRef = ref(null); const terminalStatus = ref('保存并选择一台服务器后即可建立 SSH 连接。'); const form = reactive({ hostName: '', host: '', port: 22, username: '', password: '' }); let term; let fit; let socket;
async function load() { const result = await getSshHostsApi(); hosts.value = result.data; }
async function connect(host) { activeHost.value = host; terminalStatus.value = '正在建立加密连接…'; await nextTick(); if (!term) { term = new Terminal({ cursorBlink: true, theme: { background: '#0b1220', foreground: '#d7e1f4' } }); fit = new FitAddon(); term.loadAddon(fit); term.open(terminalRef.value); term.onData((data) => socket?.emit('webssh:input', data)); } fit.fit(); term.clear(); term.writeln(`Connecting to ${host.host_name}…`); socket?.emit('webssh:connect', { hostId: host.id }); }
async function save() { saving.value = true; try { const result = await saveSshHostApi(form); dialogVisible.value = false; Object.assign(form, { hostName: '', host: '', port: 22, username: '', password: '' }); await load(); await connect(hosts.value.find((item) => item.id === result.data.id)); ElMessage.success('SSH 主机已安全保存'); } finally { saving.value = false; } }
async function remove(host) { const ok = await ElMessageBox.confirm(`删除“${host.host_name}”的保存配置吗？`, '删除 SSH 主机', { type: 'warning' }).catch(() => false); if (!ok) return; await deleteSshHostApi(host.id); if (activeHost.value?.id === host.id) { activeHost.value = null; term?.clear(); } await load(); ElMessage.success('SSH 主机配置已删除'); }
onMounted(async () => { await load(); socket = getRealtimeSocket(); if (!socket) { terminalStatus.value = '实时连接未就绪，请刷新后重试。'; return; } socket.on('webssh:data', (data) => term?.write(data)); socket.on('webssh:ready', ({ hostName }) => { terminalStatus.value = `已连接：${hostName}`; term?.writeln(''); }); socket.on('webssh:error', ({ message }) => { terminalStatus.value = message; term?.writeln(`\r\nError: ${message}`); }); socket.on('webssh:closed', () => { terminalStatus.value = 'SSH 会话已关闭'; }); }); onBeforeUnmount(() => { socket?.off('webssh:data'); socket?.off('webssh:ready'); socket?.off('webssh:error'); socket?.off('webssh:closed'); term?.dispose(); });
</script>
